
#######################################################################
############################ Caesar Cipher ############################
#######################################################################

#----------------------#
#   Cipher Algorithm   #
#----------------------#

from . import languages as Languages
alphabet = Languages.alphabet


print("Loading Caesar Cipher Algorithm...")

# Caesar Key Generator

def caesar_key(offset): # The Ceasar key generator based on a given offset 
  caesar = "" # The Caesar alphabet to be generated based on offset
  offset_adjusted = 0
  if abs(offset) >= len(alphabet): 
    offset_adjusted = offset % len(alphabet) # If offset is greater than the number of letters in the alphabet, then divide it with the number of letters and use the remainder
  else: offset_adjusted = offset # If not, then use offset as it is
  for i in range(len(alphabet)): # Iterate through the alphabet
    caesar += alphabet[i - offset_adjusted] # Until each letter is shifted to offset and added to the Caesar alphabet
  return caesar # Return the Caesar key

# Caesar Decryptor

def caesar_decrypt(message, offset): # The Caesar Decryption algorythm based on a key generated by caesar_key

  global alphabet
  alphabet = Languages.alphabet

  decrypted_message = "" # Initialise the decrypted message string
  key = caesar_key(offset) # Generate the key based on input offset
  for i in range(len(message)): # For the entire message
    key_found = False # Flag for if message character to key match found, used later for the transmission of the non-alphabet characters
    for j in range(len(key)): # Search for a corresponding character in the key
      if message[i] == key[j]: # If match found
        decrypted_message += alphabet[j] # Use the same index as the key to give the corresponding index in the global alphabet variable, and add the indexed character to the decrypted message
        key_found = True # Flag that a key character match found
        break # Break the inner loop
      elif message[i].lower() == key[j]:  # If capitalised character found
        decrypted_message += alphabet[j].upper() # Add capitalised character to the decrypted message
        key_found = True # Flag that a key character match found
        break # Break the inner loop
      else:
        continue # If not, continue
    if key_found == False: # If a key character match not found, it means it is a non-alphabetical character
        decrypted_message += message[i] # Add the exact characted from the original message (might be punctuation, white space)
    else: continue # Continue the outer loop
  return decrypted_message # Return the decrypted message

# Caesar Encryptor

def caesar_encrypt(message, offset): # The Caesar Encryption algorythm based on a key generated by caesar_key

  global alphabet
  alphabet = Languages.alphabet

  encrypted_message = "" # Initialise the encrypted message string
  key = caesar_key(offset) # Generate the key based on input offset
  for i in range(len(message)): # For the entire message
    alphabetical_found = False # Flag for if message character to alphabetical match found, used later for the transmission of the non-alphabet characters
    for j in range(len(alphabet)): # Search for a corresponding character in the global alphabet variable
      if message[i] == alphabet[j]: # If match found
        encrypted_message += key[j] # Use the same index as the alphabet variable to give the corresponding index in the key, and add the indexed character to the encrypted message
        alphabetical_found = True # Flag that an alphabetical character match found
        break # Break the inner loop
      elif message[i].lower() == alphabet[j]: # If capitalised character found
        encrypted_message += key[j].upper() # Add capitalised character to the encrypted message
        alphabetical_found = True # Flag that an alphabetical character match found
        break # Break the inner loop
      else:
        continue # If not, continue
    if alphabetical_found == False: # If an alphabetical character match not found, it means it is a non-alphabetical character
        encrypted_message += message[i] # Add the exact characted from the original message (might be punctuation, white space)
    else: continue # Continue the outer loop
  return encrypted_message # Return the encrypted message


print("Caesar Cipher Algorithm loaded.")
